/* STRYDE V5 — progressive product and material experiences. No backend. */
(()=>{'use strict';
const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>Array.from(root.querySelectorAll(s));
const variants={solar:{title:'SOLAR',accent:'#ff6938'},ice:{title:'ICE',accent:'#69caff'},volt:{title:'VOLT',accent:'#bfff4a'},violet:{title:'VIOLET',accent:'#bb79fa'}};
let energy=1,xray=false,focus='all';
function toast(message){const n=$('#toast');if(!n)return;n.textContent=message;n.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove('show'),3000)}
function stateKeyRead(k,alt=''){try{return localStorage.getItem(k)||alt}catch{return alt}}
function stateKeyWrite(k,v){try{localStorage.setItem(k,v)}catch{}}
// Showroom atmosphere is an intentionally cheap CSS presentation: no extra 3D context.
function world(which){if(!['lab','city','terrain'].includes(which))return;$('#showroom-viewport')?.setAttribute('data-v5-world',which);window.StrydeGLB?.setWorld?.(which);$$('[data-v5-world]').forEach(b=>{const on=b.dataset.v5World===which;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});stateKeyWrite('stryde-v5-world',which)}
$$('[data-v5-world]').forEach(b=>b.addEventListener('click',()=>world(b.dataset.v5World)));world(stateKeyRead('stryde-v5-world','lab'));
// Materials controls update the actual GLB named meshes while preserving artwork fallback.
function updateMaterial(group,value){$$(`[data-v5-${group}]`).forEach(b=>{let on=b.dataset[`v5${group[0].toUpperCase()+group.slice(1)}`]===value;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});window.StrydeGLB?.setStyle?.({[group==='panel'?'panels':group]:value});stateKeyWrite('stryde-v5-'+group,value)}
['panel','stitch'].forEach(group=>{const saved=stateKeyRead('stryde-v5-'+group,group==='panel'?'chrome':'frost');$$(`[data-v5-${group}]`).forEach(b=>b.addEventListener('click',()=>updateMaterial(group,b.getAttribute('data-v5-'+group))));updateMaterial(group,['panel'].includes(group)&&!['chrome','shadow','gold'].includes(saved)?'chrome':saved)});
const slider=$('#v5-energy');if(slider){slider.value=stateKeyRead('stryde-v5-energy','100');const update=()=>{energy=Math.max(0,Math.min(1,Number(slider.value)/100));$('#v5-energy-out').textContent=slider.value+'%';window.StrydeGLB?.setStyle?.({energy});stateKeyWrite('stryde-v5-energy',slider.value)};slider.addEventListener('input',update);update()}
$('#v5-share-design')?.addEventListener('click',async()=>{const data={panel:$('.v5-choice-row [data-v5-panel].active')?.dataset.v5Panel||'chrome',stitch:$('.v5-choice-row [data-v5-stitch].active')?.dataset.v5Stitch||'frost',energy:Math.round(energy*100)};const url=new URL(location.href);url.searchParams.set('atelier',btoa(JSON.stringify(data)).replaceAll('=',''));try{await navigator.clipboard.writeText(url.href);toast('CUSTOM ATELIER LINK COPIED')}catch{prompt('Copy your design link:',url.href)}});
try{const raw=new URLSearchParams(location.search).get('atelier');if(raw){const data=JSON.parse(atob(raw));if(['chrome','shadow','gold'].includes(data.panel))updateMaterial('panel',data.panel);if(['frost','dark','ember'].includes(data.stitch))updateMaterial('stitch',data.stitch);if(Number.isFinite(data.energy)&&slider){slider.value=Math.min(100,Math.max(0,data.energy));slider.dispatchEvent(new Event('input'))}}}catch{}
// Technical X-ray: genuine shader-controlled transparency + named mesh highlighting.
const focuses={all:['FULL STRUCTURE','View the complete sculpted original concept.'],upper:['ENGINEERED KNIT','Fine textile weave, collar and lacing geometry.'],chassis:['CARBON EXOSKELETON','External wing structure and heel stabilizing ribs.'],cushion:['ENERGY CELL','Air window structures and illuminated cushioning layers.'],traction:['MULTI-ZONE GRIP','Raised rubber tread islands and outsole ridge geometry.']};
function setFocus(value){if(!focuses[value])return;focus=value;$$('[data-v5-focus]').forEach(b=>{const on=b.dataset.v5Focus===value;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});window.StrydeGLB?.setHighlight?.(value);const info=$('#v5-hotspot-info');if(info){const [t,p]=focuses[value];info.querySelector('strong').textContent=t;info.querySelector('p').textContent=p}}
$$('[data-v5-focus]').forEach(b=>b.addEventListener('click',()=>setFocus(b.dataset.v5Focus)));
$$('[data-v5-hotspot]').forEach(b=>b.addEventListener('click',()=>{setFocus(b.dataset.v5Hotspot);const [title]=focuses[focus];toast(title+' / SEE TECHNOLOGY LAB FOR X-RAY')}));
const xrayButton=$('#v5-xray-toggle');xrayButton?.addEventListener('click',()=>{xray=!xray;xrayButton.setAttribute('aria-pressed',String(xray));xrayButton.textContent=xray?'◉ X-RAY ON':'◈ X-RAY OFF';window.StrydeGLB?.setXray?.(xray);if(!$('#tech-model')?.dataset.modelReady)toast('ACTIVATE 3D INSPECTION TO VIEW X-RAY MATERIALS')});
$('#v5-activate-tech')?.addEventListener('click',async()=>{const btn=$('#v5-activate-tech');if(!window.StrydeGLB?.activate){toast('3D RENDERER NOT AVAILABLE');return}btn.disabled=true;btn.textContent='LOADING 3D…';try{await window.StrydeGLB.activate('tech');window.StrydeGLB.setXray(xray);window.StrydeGLB.setHighlight(focus);btn.textContent='3D INSPECTION ACTIVE ✓'}catch{btn.textContent='3D UNAVAILABLE / IMAGE FALLBACK'}finally{btn.disabled=false}});
// Side-by-side colorway preview. Single-artwork geometry, no invented performance figures.
for(const side of ['left','right']){$(`#v5-compare-${side}`)?.addEventListener('change',e=>{const variant=variants[e.target.value];if(!variant)return;const img=$(`#v5-${side}-img`);img.src=`images/design-${e.target.value}.webp`;img.alt=`STRYDE Aerodyne ${variant.title} colorway`; $(`#v5-${side}-title`).textContent='AERODYNE / '+variant.title;});}
// Graphics preference. On iPhone keep the hardware-safe opt-in regardless of user preference.
const dock=$('#v5-perf-button'),menu=$('#v5-perf-menu');let quality=stateKeyRead('stryde-v5-quality','auto');dock?.addEventListener('click',()=>{menu.hidden=!menu.hidden;dock.setAttribute('aria-expanded',String(!menu.hidden))});
$$('[data-v5-quality]').forEach(b=>b.addEventListener('click',()=>{const requested=b.dataset.v5Quality;if(!['auto','lite','cinema'].includes(requested))return;stateKeyWrite('stryde-v5-quality',requested);menu.hidden=true;dock.setAttribute('aria-expanded','false');dock.textContent=`◈ GRAPHICS / ${requested.toUpperCase()}`;if(requested==='cinema'&&window.STRYDE_LOW_POWER)toast('YOUR DEVICE RETAINS SAFETY LIMITS');else toast('GRAPHICS PREFERENCE SAVED / RELOAD FOR NEW SETTINGS')}));
if(dock)dock.textContent=`◈ GRAPHICS / ${quality.toUpperCase()}`;document.addEventListener('click',e=>{if(menu&&!menu.hidden&&!e.target.closest('.v5-perf-dock')){menu.hidden=true;dock.setAttribute('aria-expanded','false')}});
// WebXR/Scene Viewer/Quick Look handoff is loaded only when visitor asks, to avoid Safari memory crash.
const arModal=$('#v5-ar-modal'),arStage=$('#v5-ar-stage'),arStatus=$('#v5-ar-status');let arLoading=false,arOpened=false;
function closeAR(){arModal?.setAttribute('aria-hidden','true');const model=arStage?.querySelector('model-viewer');if(model){model.pause?.();model.remove()}if(arStage&&!arStage.querySelector('img'))arStage.innerHTML='<img src="images/design-solar.webp" alt="STRYDE sneaker preview" />';arOpened=false;document.body.style.overflow=''}
$('#v5-ar-close')?.addEventListener('click',closeAR);arModal?.addEventListener('click',e=>{if(e.target===arModal)closeAR()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&arModal?.getAttribute('aria-hidden')==='false')closeAR()});
$('#v5-open-ar')?.addEventListener('click',async()=>{if(arLoading)return;arModal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';arOpened=true;arStatus.textContent='Checking AR compatibility…';if(!window.isSecureContext){arStatus.textContent='AR requires HTTPS. This preview remains available in 2D.';return}arLoading=true;try{
 if(!customElements.get('model-viewer')){await import('https://cdn.jsdelivr.net/npm/@google/model-viewer@4.1.0/dist/model-viewer.min.js')}
 if(!arOpened)return;
 arStage.innerHTML='<model-viewer id="v5-ar-model" src="models/aerodyne-v5.glb" alt="3D STRYDE sneaker concept" camera-controls interaction-prompt="auto" shadow-intensity="0.5" exposure="1.1" auto-rotate ar ar-modes="webxr scene-viewer quick-look" style="width:100%;height:100%;background:transparent"></model-viewer>';
 const mv=$('#v5-ar-model');mv.addEventListener('load',()=>{if(!arOpened)return;arStatus.textContent=mv.canActivateAR?'AR READY — TAP THE VIEW IN YOUR SPACE ICON':'3D PREVIEW ACTIVE. AR MAY BE UNAVAILABLE ON THIS DEVICE.';},{once:true});mv.addEventListener('error',()=>{arStatus.textContent='3D MODEL COULD NOT LOAD — CHECK YOUR CONNECTION.'},{once:true});
 }catch(e){arStatus.textContent='AR PREVIEW IS NOT SUPPORTED HERE. THE NORMAL PRODUCT VIEW REMAINS AVAILABLE.';console.warn('STRYDE AR unavailable',e.message)}finally{arLoading=false}});
$('#v5-open-film')?.addEventListener('click',()=>$('#open-film')?.click());
// Page transitions and scroll reveals intentionally use only compositing-friendly DOM animations.
if(!matchMedia('(prefers-reduced-motion:reduce)').matches&&'IntersectionObserver'in window){const observer=new IntersectionObserver((entries)=>{for(const e of entries)if(e.isIntersecting){e.target.classList.add('v5-visible');observer.unobserve(e.target)}},{threshold:.06,rootMargin:'40px'});$$('.v5-compare-card,.v5-experience-grid article').forEach(e=>{e.classList.add('v5-reveal');observer.observe(e)})}
window.addEventListener('pagehide',closeAR,{once:true});
})();
