(()=>{'use strict';const csrf=window.STRYDE_ADMIN_CSRF;const el=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(action,body){const r=await fetch('../api/index.php?action='+encodeURIComponent(action),{credentials:'same-origin',headers:{'Accept':'application/json',...(body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{})},...(body?{method:'POST',body:JSON.stringify(body)}:{})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Request failed');return j.data;}
const msg=t=>{el('admin-message').textContent=t};const cash=n=>'$'+(Number(n)/100).toFixed(2);
async function load(){try{
 const [s,orders,products,settings]=await Promise.all([api('admin_dashboard'),api('admin_orders'),api('admin_products'),api('admin_settings')]);
 const sf=el('admin-settings');for(const [k,v] of Object.entries({standard_cents:settings.standard_cents,express_cents:settings.express_cents,free_threshold_cents:settings.free_threshold_cents,bc_rate:settings.estimated_tax_rates.BC??.12})){if(sf.elements.namedItem(k))sf.elements.namedItem(k).value=v;}
 el('admin-stats').innerHTML=[['Customers',s.customers],['Orders',s.order_count],['Verified paid revenue',cash(s.revenue_cents)],['Products',s.products]].map(([n,v])=>`<div class="admin-stat"><small>${esc(n)}</small><b>${esc(v)}</b></div>`).join('');
 el('admin-orders').innerHTML=orders.length?orders.map(o=>`<tr data-order="${Number(o.id)}"><td><b>${esc(o.public_id)}</b><br><small>${esc(o.created_at)}</small></td><td>${esc(o.customer_email)}<br><small>${esc([o.shipping?.recipient,o.shipping?.address,o.shipping?.city,o.shipping?.province,o.shipping?.postal_code].filter(Boolean).join(', '))}</small></td><td>${esc(o.payment_status)}</td><td>${cash(o.total_cents)}</td><td><select class="order-status">${['demo','processing','shipped','delivered','cancelled','manual_review'].map(x=>`<option value="${x}" ${x===o.status?'selected':''}>${x}</option>`).join('')}</select></td><td><input class="tracking-carrier" placeholder="Carrier" value="${esc(o.tracking_carrier)}"><input class="tracking-number" placeholder="Tracking number" value="${esc(o.tracking_number)}"></td><td><button data-save-order>Save</button></td></tr>`).join(''):'<tr><td colspan="7">No orders yet</td></tr>';
 el('admin-products').innerHTML=products.map(p=>`<tr data-variant="${Number(p.variant_id)}"><td>${esc(p.sku)}</td><td>${esc(p.name)}</td><td><input class="product-price" type="number" min="0" value="${Number(p.price_cents)}" aria-label="Price cents"><button data-save-price data-sku="${esc(p.sku)}" data-name="${esc(p.name)}" data-active="${Number(p.active)}">Price</button></td><td>${esc(p.size_us)} / ${esc(p.colorway)}</td><td><input class="variant-stock" type="number" min="0" value="${Number(p.stock)}" aria-label="Stock"></td><td><button data-save-stock>Save stock</button></td></tr>`).join('');
 }catch(e){msg(e.message);}}
document.addEventListener('click',async e=>{const target=e.target.closest('button');if(!target)return;const tr=target.closest('tr');try{
 if(target.matches('[data-save-order]')){await api('admin_order_update',{id:Number(tr.dataset.order),status:tr.querySelector('.order-status').value,tracking_carrier:tr.querySelector('.tracking-carrier').value,tracking_number:tr.querySelector('.tracking-number').value});msg('Order updated');}
 if(target.matches('[data-save-stock]')){await api('admin_stock',{variant_id:Number(tr.dataset.variant),stock:Number(tr.querySelector('.variant-stock').value)});msg('Inventory updated');}
 if(target.matches('[data-save-price]')){await api('admin_products',{sku:target.dataset.sku,name:target.dataset.name,active:Number(target.dataset.active),price_cents:Number(tr.querySelector('.product-price').value)});msg('Product price updated');}
 }catch(err){msg(err.message)}});
el('admin-settings').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const data=Object.fromEntries(new FormData(f));try{const old=await api('admin_settings');await api('admin_settings',{standard_cents:Number(data.standard_cents),express_cents:Number(data.express_cents),free_threshold_cents:Number(data.free_threshold_cents),estimated_tax_rates:{...old.estimated_tax_rates,BC:Number(data.bc_rate)}});msg('Shipping and estimate settings saved.');}catch(err){msg(err.message)}});
load();
})();
