<?php
declare(strict_types=1);
require dirname(__DIR__).'/api/bootstrap.php';
header('X-Content-Type-Options: nosniff');
header('Cache-Control: no-store');
try{if(!configured()){require_once dirname(__DIR__).'/api/demo.php';session_start_secure();$me=demo_user();}else{$me=user();}}catch(Throwable $e){$me=null;}
if(!$me||$me['role']!=='admin'){
  http_response_code(403);echo '<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>STRYDE • Admin Access</title><style>body{background:#101217;color:#f4f3ed;font:16px system-ui;padding:10vh 9%}a{color:#ff793a}</style><h1>Admin access required</h1><p>Sign in with an administrator account on the STRYDE storefront first.</p><a href="../">Return to STRYDE</a>';exit;
}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>STRYDE / ADMIN</title><link rel="stylesheet" href="../commerce.css?v=6.0"><style>
body{margin:0;background:#0c0e11;color:#ececed;font:14px system-ui,sans-serif}.admin-shell{max-width:1480px;margin:auto;padding:32px clamp(16px,3vw,60px)}.admin-heading{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #34383b;padding-bottom:20px}.admin-heading strong{font-size:29px;letter-spacing:-.07em}.admin-heading strong i{color:#ff713d;font-style:normal}.admin-heading a{color:#eaeaea}.admin-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:25px 0}.admin-stat{background:#181b1e;border:1px solid #303539;padding:20px}.admin-stat b{display:block;font-size:29px;margin:8px 0}.admin-stat small{color:#aeb8bb}.admin-section{margin:34px 0}.admin-section h2{font-size:20px}.admin-scroll{overflow-x:auto}.admin-table{width:100%;min-width:760px;border-collapse:collapse}.admin-table td,.admin-table th{border-bottom:1px solid #303539;padding:12px;text-align:left}.admin-table th{font-size:10px;color:#a9acae;letter-spacing:.13em}.admin-table input,.admin-table select{background:#151719;color:#fff;border:1px solid #515a60;padding:10px;width:100%;box-sizing:border-box}.admin-table button,.admin-btn{background:#ff723f;color:#171719;padding:11px 17px;border:0;cursor:pointer;font-weight:800}.admin-note{color:#b3b5b8;font-size:13px}.admin-table td{vertical-align:middle}#admin-settings label{display:flex;flex-direction:column;gap:7px;color:#cad0d3}#admin-settings input{padding:12px;background:#1c2024;color:white;border:1px solid #596067;font-size:15px}#admin-message{position:sticky;top:0;padding:8px;color:#ff9d70;min-height:32px;background:#0c0e11} @media(max-width:720px){.admin-grid{grid-template-columns:repeat(2,1fr)}.admin-heading strong{font-size:23px}}
</style></head><body><main class="admin-shell"><header class="admin-heading"><strong>STRYDE<i>®</i> / COMMAND</strong><div><span><?=htmlspecialchars($me['email'],ENT_QUOTES,'UTF-8')?></span> &nbsp; <a href="../">Storefront ↗</a></div></header><p id="admin-message" role="status"></p><div class="admin-grid" id="admin-stats"><div class="admin-stat">Loading dashboard…</div></div><section class="admin-section"><h2>Orders &amp; fulfillment</h2><p class="admin-note">Demo orders are not payments and cannot be fulfilled. Paid orders require a verified Stripe webhook.</p><div class="admin-scroll"><table class="admin-table"><thead><tr><th>Order</th><th>Customer / Address</th><th>Payment</th><th>Total</th><th>Status</th><th>Tracking</th><th>Action</th></tr></thead><tbody id="admin-orders"></tbody></table></div></section><section class="admin-section"><h2>Products &amp; inventory</h2><p class="admin-note">Inventory and prices are managed on the server, not in browser source files. Seed quantities are simulated.</p><div class="admin-scroll"><table class="admin-table"><thead><tr><th>SKU</th><th>Product</th><th>Price (CAD cents)</th><th>Size / Colorway</th><th>Stock</th><th>Action</th></tr></thead><tbody id="admin-products"></tbody></table></div></section><section class="admin-section"><h2>Shipping &amp; tax configuration</h2><p class="admin-note">Rates are editable for DEMO estimates. Review Canadian tax obligations and configure Stripe Tax before accepting live sales.</p>
<form id="admin-settings" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:15px"><label>Standard shipping (CAD cents)<input type="number" name="standard_cents" min="0" max="100000" required></label><label>Express shipping (CAD cents)<input type="number" name="express_cents" min="0" max="100000" required></label><label>Free standard shipping threshold (CAD cents)<input type="number" name="free_threshold_cents" min="0" max="100000" required></label><label>BC estimated tax rate (decimal)<input type="number" name="bc_rate" step="0.001" min="0" max="0.3" required></label><button type="submit" class="admin-btn">SAVE SHIPPING &amp; TAX ESTIMATES</button></form></section></main><script>window.STRYDE_ADMIN_CSRF=<?=json_encode($_SESSION['csrf'])?>;</script><script src="admin.js?v=6.0" defer></script></body></html>