<?php
declare(strict_types=1);
// Self-contained, server-side SQLite demo commerce. Does not process payments.
require_once __DIR__.'/bootstrap.php';
function demo_db(): PDO {
 static $pdo;
 if($pdo instanceof PDO) return $pdo;
 if(!extension_loaded('pdo_sqlite')) throw new RuntimeException('PHP pdo_sqlite extension is required for automatic demo setup. Enable it in cPanel PHP Selector.');
 $root=dirname(__DIR__,3).'/stryde-demo-private';
 if(!is_dir($root) && !mkdir($root,0700,true) && !is_dir($root)) throw new RuntimeException('Cannot create private data directory outside public_html.');
 $path=$root.'/store.sqlite';
 $pdo=new PDO('sqlite:'.$path,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
 $pdo->exec('PRAGMA busy_timeout=5000; PRAGMA foreign_keys=ON;');
 $pdo->exec("CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'customer',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,sku TEXT NOT NULL UNIQUE,name TEXT NOT NULL,description TEXT,price_cents INTEGER NOT NULL,active INTEGER DEFAULT 1);
 CREATE TABLE IF NOT EXISTS variants(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER NOT NULL,size_us TEXT NOT NULL,colorway TEXT NOT NULL,stock INTEGER NOT NULL DEFAULT 10,UNIQUE(product_id,size_us,colorway));
 CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,public_id TEXT NOT NULL UNIQUE,user_id INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'demo',payment_status TEXT NOT NULL DEFAULT 'demo',subtotal_cents INTEGER NOT NULL,shipping_cents INTEGER NOT NULL,estimated_tax_cents INTEGER NOT NULL,total_cents INTEGER NOT NULL,shipping_method TEXT NOT NULL,shipping_json TEXT NOT NULL,tracking_carrier TEXT DEFAULT '',tracking_number TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,product_id INTEGER NOT NULL,variant_id INTEGER NOT NULL,name TEXT NOT NULL,size_us TEXT NOT NULL,colorway TEXT NOT NULL,finish TEXT NOT NULL,materials_json TEXT,quantity INTEGER NOT NULL,price_cents INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS store_settings(setting_key TEXT PRIMARY KEY,setting_value TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS login_attempts(id INTEGER PRIMARY KEY AUTOINCREMENT,key_hash TEXT NOT NULL,attempted_at INTEGER NOT NULL);");
 $seed=[['aerodyne','AERODYNE ONE',22000,['solar','ice','volt','violet']],['volt','VOLT PRO',24500,['solar']],['nexus','NEXUS',21000,['ice']],['phantom','PHANTOM',23000,['violet']]];
 foreach($seed as [$sku,$name,$price,$colors]){
  $pdo->prepare('INSERT OR IGNORE INTO products(sku,name,description,price_cents) VALUES(?,?,?,?)')->execute([$sku,$name,'Demo concept sneaker',$price]);
  $pid=(int)$pdo->query('SELECT id FROM products WHERE sku='.$pdo->quote($sku))->fetchColumn();
  foreach($colors as $color)foreach(['7','8','9','10','11','12'] as $size)$pdo->prepare('INSERT OR IGNORE INTO variants(product_id,size_us,colorway,stock) VALUES(?,?,?,10)')->execute([$pid,$size,$color]);
 }
 foreach(['standard_cents'=>'1500','express_cents'=>'2900','free_threshold_cents'=>'15000','estimated_tax_rates'=>json_encode(['AB'=>.05,'BC'=>.12,'MB'=>.12,'NB'=>.15,'NL'=>.15,'NS'=>.14,'NT'=>.05,'NU'=>.05,'ON'=>.13,'PE'=>.15,'QC'=>.14975,'SK'=>.11,'YT'=>.05])] as $k=>$v)$pdo->prepare('INSERT OR IGNORE INTO store_settings(setting_key,setting_value) VALUES(?,?)')->execute([$k,$v]);
 @chmod($path,0600);return $pdo;
}
function demo_user(): ?array {if(empty($_SESSION['demo_uid']))return null;$q=demo_db()->prepare('SELECT id,name,email,role,created_at FROM users WHERE id=?');$q->execute([$_SESSION['demo_uid']]);return $q->fetch()?:null;}
function demo_admin(): array {$u=demo_user();if(!$u||$u['role']!=='admin')api_error('Administrator only',403);return $u;}
function demo_setting(string $key,string $fallback): string {$q=demo_db()->prepare('SELECT setting_value FROM store_settings WHERE setting_key=?');$q->execute([$key]);return (string)($q->fetchColumn()?:$fallback);}
function demo_quote(array $items,string $province,string $shippingMethod): array {
 if(!in_array($shippingMethod,['standard','express'],true))api_error('Invalid shipping method');
 if(!preg_match('/^[A-Z]{2}$/',$province))api_error('Choose province');
 if(count($items)<1||count($items)>30)api_error('Add an item to the shopping bag');
 $lines=[];$sub=0;$totals=[];$select=demo_db()->prepare('SELECT p.id product_id,p.name,p.price_cents,v.id variant_id,v.stock FROM products p JOIN variants v ON v.product_id=p.id WHERE p.sku=? AND v.size_us=? AND v.colorway=? AND p.active=1');
 foreach($items as $item){if(!is_array($item))api_error('Invalid item');$sku=(string)($item['id']??'');$size=(string)($item['size']??'');$color=(string)($item['color']??'solar');$qty=filter_var($item['qty']??null,FILTER_VALIDATE_INT);if(!in_array($size,['7','8','9','10','11','12'],true)||!$qty||$qty<1||$qty>10)api_error('Invalid size or quantity');$select->execute([$sku,$size,$color]);$r=$select->fetch();if(!$r)api_error('Selected sneaker is unavailable');$vid=(int)$r['variant_id'];$totals[$vid]=($totals[$vid]??0)+$qty;if($totals[$vid]>(int)$r['stock'])api_error('Not enough demo stock');$finish=(string)($item['finish']??'reflective');if(!in_array($finish,['matte','reflective'],true))api_error('Invalid finish');$materials=$item['materials']??null;if($materials!==null&&!is_array($materials))api_error('Invalid materials');$lines[]=['product_id'=>(int)$r['product_id'],'variant_id'=>$vid,'name'=>$r['name'],'size'=>$size,'color'=>$color,'finish'=>$finish,'materials'=>$materials,'quantity'=>$qty,'unit_cents'=>(int)$r['price_cents']];$sub+=$qty*(int)$r['price_cents'];}
 $standard=(int)demo_setting('standard_cents','1500');$express=(int)demo_setting('express_cents','2900');$threshold=(int)demo_setting('free_threshold_cents','15000');$ship=$shippingMethod==='express'?$express:($sub>=$threshold?0:$standard);$rates=json_decode(demo_setting('estimated_tax_rates','{}'),true)?:[];$rate=(float)($rates[$province]??.05);$tax=(int)round(($sub+$ship)*$rate);
 return ['lines'=>$lines,'subtotal_cents'=>$sub,'shipping_cents'=>$ship,'estimated_tax_cents'=>$tax,'total_cents'=>$sub+$ship+$tax,'shipping_method'=>$shippingMethod,'tax_disclaimer'=>'Illustrative demo estimate; not a tax invoice.','currency'=>'CAD'];
}
function demo_route(): never {
 header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');
 session_start_secure();$method=$_SERVER['REQUEST_METHOD']??'GET';$a=(string)($_GET['action']??'session');
 try{demo_db();}catch(Throwable $e){api_error('Automatic demo storage unavailable: '.$e->getMessage(),503);}
 if($method==='POST')csrf_guard();$db=demo_db();$u=demo_user();
 if($a==='session'&&$method==='GET')json_response(['configured'=>true,'demo'=>true,'user'=>$u,'csrf'=>$_SESSION['csrf'],'payment_mode'=>'Demo only — no payments']);
 if($a==='catalog'&&$method==='GET')json_response($db->query('SELECT sku,name,description,price_cents FROM products WHERE active=1')->fetchAll());
 if($a==='register'&&$method==='POST'){$b=body_json();$name=trim((string)($b['name']??''));$email=strtolower(trim((string)($b['email']??'')));$pw=(string)($b['password']??'');if(mb_strlen($name)<2||mb_strlen($name)>120||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($pw)<12||strlen($pw)>256)api_error('Enter a name, valid email and password (12+ characters)');try{$db->prepare("INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,'customer')")->execute([$name,$email,password_hash($pw,PASSWORD_DEFAULT)]);}catch(PDOException $e){api_error('Email is already registered',409);}session_regenerate_id(true);$_SESSION['demo_uid']=(int)$db->lastInsertId();$_SESSION['csrf']=bin2hex(random_bytes(24));json_response(['user'=>demo_user(),'csrf'=>$_SESSION['csrf']],201);}
 if($a==='login'&&$method==='POST'){$b=body_json();$email=strtolower(trim((string)($b['email']??'')));$pw=(string)($b['password']??'');$key=hash('sha256',$email.'|'.($_SERVER['REMOTE_ADDR']??''));$db->prepare('DELETE FROM login_attempts WHERE attempted_at < ?')->execute([time()-900]);$q=$db->prepare('SELECT COUNT(*) FROM login_attempts WHERE key_hash=?');$q->execute([$key]);if((int)$q->fetchColumn()>=7)api_error('Too many attempts, try again later.',429);$q=$db->prepare('SELECT id,password_hash FROM users WHERE email=?');$q->execute([$email]);$found=$q->fetch();if(!$found||!password_verify($pw,$found['password_hash'])){$db->prepare('INSERT INTO login_attempts(key_hash,attempted_at) VALUES(?,?)')->execute([$key,time()]);api_error('Incorrect email or password',401);} $db->prepare('DELETE FROM login_attempts WHERE key_hash=?')->execute([$key]);session_regenerate_id(true);$_SESSION['demo_uid']=(int)$found['id'];$_SESSION['csrf']=bin2hex(random_bytes(24));json_response(['user'=>demo_user(),'csrf'=>$_SESSION['csrf']]);}
 if($a==='logout'&&$method==='POST'){$_SESSION=[];session_regenerate_id(true);$_SESSION['csrf']=bin2hex(random_bytes(24));json_response(['logged_out'=>true,'csrf'=>$_SESSION['csrf']]);}
 if($a==='quote'&&$method==='POST'){$b=body_json();json_response(demo_quote($b['items']??[],strtoupper((string)($b['province']??'BC')),(string)($b['shipping_method']??'standard')));}
 if($a==='checkout'&&$method==='POST'){
  if(!$u)api_error('Sign in to place a demo order',401);$b=body_json();$address=trim((string)($b['address']??''));$city=trim((string)($b['city']??''));$postal=trim((string)($b['postal_code']??''));$recipient=trim((string)($b['recipient']??''));$province=strtoupper((string)($b['province']??''));if(strlen($address)<5||strlen($city)<2||strlen($postal)<3||strlen($recipient)<2||strlen($address)>190||strlen($recipient)>120)api_error('Complete shipping details');$quote=demo_quote($b['items']??[],$province,(string)($b['shipping_method']??'standard'));$public='DEMO-'.strtoupper(bin2hex(random_bytes(5)));$shipping=['address'=>$address,'city'=>$city,'postal_code'=>$postal,'recipient'=>$recipient,'province'=>$province,'country'=>'CA'];$db->beginTransaction();try{$q=$db->prepare("INSERT INTO orders(public_id,user_id,status,payment_status,subtotal_cents,shipping_cents,estimated_tax_cents,total_cents,shipping_method,shipping_json) VALUES(?,?,'demo','demo',?,?,?,?,?,?)");$q->execute([$public,$u['id'],$quote['subtotal_cents'],$quote['shipping_cents'],$quote['estimated_tax_cents'],$quote['total_cents'],$quote['shipping_method'],json_encode($shipping)]);$order=(int)$db->lastInsertId();$q=$db->prepare('INSERT INTO order_items(order_id,product_id,variant_id,name,size_us,colorway,finish,materials_json,quantity,price_cents) VALUES(?,?,?,?,?,?,?,?,?,?)');foreach($quote['lines'] as $l)$q->execute([$order,$l['product_id'],$l['variant_id'],$l['name'],$l['size'],$l['color'],$l['finish'],json_encode($l['materials']),$l['quantity'],$l['unit_cents']]);$db->commit();}catch(Throwable $e){$db->rollBack();throw $e;}json_response(['mode'=>'demo','order_id'=>$public,'message'=>'Demo order created. No payment charged or physical item shipped.','quote'=>$quote],201);
 }
 if($a==='orders'&&$method==='GET'){if(!$u)api_error('Sign in first',401);$q=$db->prepare('SELECT * FROM orders WHERE user_id=? ORDER BY id DESC');$q->execute([$u['id']]);$orders=$q->fetchAll();$items=$db->prepare('SELECT name,size_us,colorway,quantity FROM order_items WHERE order_id=?');foreach($orders as &$o){$items->execute([$o['id']]);$o['items']=$items->fetchAll();}json_response($orders);}
 if(str_starts_with($a,'admin_')){demo_admin();
  if($a==='admin_dashboard'&&$method==='GET')json_response(['customers'=>(int)$db->query("SELECT count(*) FROM users WHERE role='customer'")->fetchColumn(),'order_count'=>(int)$db->query('SELECT count(*) FROM orders')->fetchColumn(),'revenue_cents'=>0,'products'=>(int)$db->query('SELECT count(*) FROM products')->fetchColumn()]);
  if($a==='admin_orders'&&$method==='GET'){$rows=$db->query('SELECT o.*,u.email customer_email FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.id DESC')->fetchAll();foreach($rows as &$o)$o['shipping']=json_decode($o['shipping_json'],true);json_response($rows);}
  if($a==='admin_products'&&$method==='GET')json_response($db->query('SELECT p.sku,p.name,p.price_cents,p.active,v.id variant_id,v.size_us,v.colorway,v.stock FROM products p JOIN variants v ON v.product_id=p.id ORDER BY p.id,v.id')->fetchAll());
  if($a==='admin_settings') {if($method==='GET')json_response(['standard_cents'=>(int)demo_setting('standard_cents','1500'),'express_cents'=>(int)demo_setting('express_cents','2900'),'free_threshold_cents'=>(int)demo_setting('free_threshold_cents','15000'),'estimated_tax_rates'=>json_decode(demo_setting('estimated_tax_rates','{}'),true)]);$b=body_json();foreach(['standard_cents','express_cents','free_threshold_cents'] as $k){$n=filter_var($b[$k]??null,FILTER_VALIDATE_INT);if($n===false||$n<0||$n>100000)api_error('Invalid shipping amount');$db->prepare('UPDATE store_settings SET setting_value=? WHERE setting_key=?')->execute([(string)$n,$k]);}if(isset($b['estimated_tax_rates'])){if(!is_array($b['estimated_tax_rates']))api_error('Invalid rates');$rates=[];foreach($b['estimated_tax_rates'] as $k=>$v){if(!preg_match('/^[A-Z]{2}$/',$k)||!is_numeric($v)||(float)$v<0||(float)$v>.3)api_error('Invalid rate');$rates[$k]=(float)$v;}$db->prepare('UPDATE store_settings SET setting_value=? WHERE setting_key=?')->execute([json_encode($rates),'estimated_tax_rates']);}json_response(['saved'=>true]);}
  if($a==='admin_products'&&$method==='POST'){$b=body_json();$sku=(string)($b['sku']??'');$price=filter_var($b['price_cents']??null,FILTER_VALIDATE_INT);if($price===false||$price<0||$price>10000000)api_error('Invalid price');$db->prepare('UPDATE products SET price_cents=? WHERE sku=?')->execute([$price,$sku]);json_response(['saved'=>true]);}
  if($a==='admin_stock'&&$method==='POST'){$b=body_json();$id=filter_var($b['variant_id']??null,FILTER_VALIDATE_INT);$stock=filter_var($b['stock']??null,FILTER_VALIDATE_INT);if(!$id||$stock===false||$stock<0||$stock>99999)api_error('Invalid stock');$db->prepare('UPDATE variants SET stock=? WHERE id=?')->execute([$stock,$id]);json_response(['saved'=>true]);}
  if($a==='admin_order_update'&&$method==='POST'){$b=body_json();$id=filter_var($b['id']??null,FILTER_VALIDATE_INT);$status=(string)($b['status']??'');if(!$id||!in_array($status,['demo','processing','shipped','delivered','cancelled','manual_review'],true))api_error('Invalid status');$db->prepare('UPDATE orders SET status=?,tracking_carrier=?,tracking_number=? WHERE id=?')->execute([$status,mb_substr((string)($b['tracking_carrier']??''),0,80),mb_substr((string)($b['tracking_number']??''),0,140),$id]);json_response(['saved'=>true]);}
 }
 api_error('Unknown action',404);
}