CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, role ENUM('customer','admin') NOT NULL DEFAULT 'customer',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS products (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, sku VARCHAR(40) NOT NULL UNIQUE,
 name VARCHAR(120) NOT NULL, description TEXT, price_cents INT UNSIGNED NOT NULL,
 active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS variants (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, product_id BIGINT UNSIGNED NOT NULL,
 size_us VARCHAR(5) NOT NULL, colorway VARCHAR(20) NOT NULL, stock INT UNSIGNED NOT NULL DEFAULT 0,
 UNIQUE KEY unique_variant(product_id,size_us,colorway),
 FOREIGN KEY (product_id) REFERENCES products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS orders (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, public_id VARCHAR(30) NOT NULL UNIQUE,
 user_id BIGINT UNSIGNED NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'cad',
 status VARCHAR(25) NOT NULL DEFAULT 'pending', payment_status VARCHAR(25) NOT NULL DEFAULT 'unpaid',
 stripe_session_id VARCHAR(255) UNIQUE NULL,
 subtotal_cents INT UNSIGNED NOT NULL, shipping_cents INT UNSIGNED NOT NULL,
 estimated_tax_cents INT UNSIGNED NOT NULL, total_cents INT UNSIGNED NOT NULL,
 shipping_method VARCHAR(20) NOT NULL, shipping_json JSON NOT NULL,
 tracking_carrier VARCHAR(80) NULL, tracking_number VARCHAR(140) NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX (user_id, created_at), FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS order_items (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, order_id BIGINT UNSIGNED NOT NULL,
 product_id BIGINT UNSIGNED NOT NULL, variant_id BIGINT UNSIGNED NOT NULL,
 name VARCHAR(120) NOT NULL, size_us VARCHAR(5) NOT NULL, colorway VARCHAR(20) NOT NULL,
 finish VARCHAR(20) NOT NULL, materials_json JSON NULL, quantity SMALLINT UNSIGNED NOT NULL,
 price_cents INT UNSIGNED NOT NULL,
 FOREIGN KEY(order_id) REFERENCES orders(id), FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(variant_id) REFERENCES variants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS login_attempts (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 key_hash CHAR(64) NOT NULL, attempted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(key_hash, attempted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS store_settings (
 setting_key VARCHAR(80) NOT NULL PRIMARY KEY,
 setting_value TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
